#!/usr/bin/env python3
"""Build data.json for ActionCity daily report — 2026-06-27 (W26, Sat)."""
import json, math

# ── helpers ─────────────────────────────────────────────────────────────────
def fmt(n, decimals=0):
    if n is None: return "—"
    if decimals == 0:
        return f"{int(round(n)):,}"
    return f"{round(n, decimals):,.{decimals}f}"

def pct(n):
    if n is None: return "—"
    sign = "+" if n >= 0 else ""
    return f"{sign}{round(n,1)}%"

def wow_arrow(n):
    return "▲" if n >= 0 else "▼"

def wow_color(n):
    return "#1f9d57" if n >= 0 else "#d6453a"

def gp_color(g):
    return "#c43b27" if g < 50 else "#1f7a55"

def stock_color(s):
    if s < 15: return "#c43b27"
    if s > 600: return "#b5740a"
    return "#2b2b33"

# ── SCALARS ─────────────────────────────────────────────────────────────────
day_net_raw     = 64090.50
last_sat_retail = 87533.09
day_bills       = 117
day_units       = 186
day_ticket      = day_net_raw / day_bills          # 547.78
day_wow         = day_net_raw / last_sat_retail - 1  # -0.268

wtd_net_raw     = 460473.00   # all-channel, from Query B W26
wtd_days        = 6
wtd_per_day     = wtd_net_raw / wtd_days

scalars = {
    # header
    "report_date_display": "27 Jun 2026",
    "report_weekday": "Sat",
    "iso_week": "26",
    "w_minus1": "25",
    "w_minus2": "24",
    "w_minus3": "23",
    "w_minus4": "22",
    "generated_at": "27 Jun 2026 22:00 (Asia/Bangkok)",
    "mode_badge": "DAILY",
    "mode_badge_color": "#F27061",
    "footer_cchaw": "CHAW Retailing Co., Ltd. &middot; Internal management report &middot; Generated by automated routine.",

    # KPI
    "day_net": fmt(day_net_raw),
    "day_bills": fmt(day_bills),
    "day_bills_split": "117 retail bills (no wholesale today)",
    "day_ticket": fmt(day_ticket),
    "day_wow_pct": f"{abs(round(day_wow*100,1))}%",
    "day_wow_arrow": wow_arrow(day_wow),
    "day_wow_color": wow_color(day_wow),

    "wtd_net": fmt(wtd_net_raw),
    "wtd_days": str(wtd_days),
    "wtd_per_day": fmt(wtd_per_day),

    "best_today_list": (
        "Upset Duck Status Display Hipper &times;14 &bull; "
        "Upset Duck Stop The Spiral &times;12 &bull; "
        "Bikini Bottom Spongebob Plush Keychain &times;12 &bull; "
        "Seal Beans Squishy &times;8 &bull; "
        "Disney Princess Pony &times;7 &bull; "
        "Upset Duck Pocket Crazy Circus &times;6 &bull; "
        "Mr. Bone Agent &times;5 &bull; "
        "Mr. Bone Strange Alliance 3.0 &times;5"
    ),

    # weekly chart labels
    "week_note": (
        "Net = invoices &minus; returns, all channels. "
        "W21 (&#3647;755k) includes a large intercompany order. "
        "Current WTD W26 (6 days, Sat close) already at &#3647;460k &mdash; tracking above prior full weeks."
    ),

    # daily branch section
    "today_branch_note": (
        "Westgate (235), E-Commerce (177), and vending locations 347/194/196/197/210 had no retail postings today."
    ),

    # 3-week branch headers
    "br_w2_label": "W23",
    "br_w1_label": "W24",
    "br_w0_label": "W25",
    "branch_note": (
        "Liberty HQ (172) W24 &#3647;90,762 inflated by a B2B/wholesale transfer. "
        "Westgate (235) and E-Commerce (177) recorded zero sales in W23&ndash;W25 &mdash; check store/POS status."
    ),

    # category mix
    "cat_note": (
        "Trailing 4 weeks from W22 (25 May). All channels including wholesale/online. "
        "GP% below 50% on both categories &mdash; review cost structure and pricing."
    ),

    # top 20
    "top_w1_label": "W24",
    "top_w0_label": "W25",
    "top_note": (
        "Wholesale (Siam Specialty): &#3647;72,439 / 309u across 12 SKUs (4 orders) in W24+W25 &mdash; excluded from ranking above."
    ),

    # reorder
    "reorder_note": (
        "Items shown: retail velocity (w1+WTD) &ge;20u AND stock &lt;90 AND cover &lt;3. "
        "Grogu Chubby Planet (stock=5) near depletion but just below the 20u velocity threshold; monitor."
    ),

    # POs
    "po_note": (
        "711 approved-PO open lines total. Largest: Upset Duck Status Display 384u &#3647;218k (POACT251200065, Dec 2025). "
        "Mimi Leisurely Elf (POACT2506, Jun 2025) &mdash; 180u open, item not selling &mdash; review/cancel."
    ),

    # dead stock
    "dead_owned_skus": "76",
    "dead_owned_value": "667,003",
    "dead_note": (
        "Owned count (76 SKUs, 337u, &#3647;667k at cost) above typical 10&ndash;20 SKU range. "
        "Sold-exclusion confirmed working (active top-sellers excluded). "
        "Some items may route to ActionCity PTE consignment &mdash; verify Jelilo series, Bearbrick premium 1000%, Laura batches."
    ),
}

# ── REPEATS ─────────────────────────────────────────────────────────────────

# -- insight_rows (6 bullets) ------------------------------------------------
insight_rows = [
    {"insight": (
        "<b>Today (retail):</b> &#3647;64,091 &mdash; &#9660;&nbsp;26.8% vs last Saturday (&#3647;87,533). "
        "WTD W26: &#3647;460,473 over 6 days (~&#3647;76,746/day all-channel)."
    )},
    {"insight": (
        "<b>Wholesale spike this WTD:</b> Wholesale (class 12) &#3647;213,876 vs &#3647;0 last week, matching Retails "
        "(&#3647;212,038). Day-level retail-only &#3647;64k is the true demand signal; wholesale is a B2B fill, not store demand."
    )},
    {"insight": (
        "<b>Branch:</b> Siam Square One leads W25 at &#3647;189,880 and is up for the 3rd consecutive week. "
        "Central Ladprao declining: W23 &#3647;53k &rarr; W24 &#3647;44k &rarr; W25 &#3647;37k (&minus;30% over 3 weeks)."
    )},
    {"insight": (
        "&#9888; <b>DARK:</b> Westgate (loc 235) recorded zero sales in W23&ndash;W25. "
        "E-Commerce (177) and HQ vending (347) also dark &mdash; check store/POS feeds."
    )},
    {"insight": (
        "<b>Reorder:</b> Fuggler Heart Care Bear Monster Plush Keychain BB &mdash; stock 36, cover 1.6 weeks. "
        "Grogu Chubby Planet BB stock=5 (nearly out, monitor for emergency reorder)."
    )},
    {"insight": (
        "<b>Dead stock return opportunity:</b> Big Box consignment 68 SKUs / 424u at cost ~&#3647;3.36M. "
        "MNT-series 49 SKUs / 3,708u (~&#3647;1.07M). Interco return 267 SKUs / 3,411u (~&#3647;1.52M). "
        "Owned/to-clear: 76 SKUs / 337u at cost &#3647;667k."
    )},
]

# -- today_branch_rows -------------------------------------------------------
loc_names = {
    "172": "Liberty (HQ)",
    "174": "Fashion Island",
    "176": "Siam Square One",
    "177": "E-Commerce",
    "194": "Rama 9 (vending)",
    "196": "Bangkapi 1 (vending)",
    "197": "Bangkapi 2 (vending)",
    "198": "Central Ladprao",
    "210": "IconSiam 6F (vending)",
    "235": "Westgate",
    "347": "HQ vending",
}

today_raw = [
    {"loc": "176", "net": 32474.68, "bills": 66, "retail_net": 32474.68, "retail_bills": 66},
    {"loc": "174", "net": 23487.79, "bills": 36, "retail_net": 23487.79, "retail_bills": 36},
    {"loc": "172", "net": 4308.41,  "bills": 6,  "retail_net": 4308.41,  "retail_bills": 6},
    {"loc": "198", "net": 3819.62,  "bills": 9,  "retail_net": 3819.62,  "retail_bills": 9},
]

today_branch_rows = []
for b in today_raw:
    ticket = b["retail_net"] / b["retail_bills"] if b["retail_bills"] else 0
    wholesale_flag = b["net"] > b["retail_net"] * 1.05
    today_branch_rows.append({
        "tb_name":   loc_names.get(b["loc"], b["loc"]),
        "tb_net":    fmt(b["net"]),
        "tb_bills":  fmt(b["bills"]),
        "tb_ticket": fmt(ticket),
        "tb_flag":   "WHOLESALE" if wholesale_flag else "",
        "tb_bg":     "#fff8f6" if wholesale_flag else "#ffffff",
        "tb_color":  "#c43b27" if wholesale_flag else "#2b2b33",
    })

# -- week_rows ---------------------------------------------------------------
week_data = [
    ("W20", 362936.34, False),
    ("W21", 755367.43, False),
    ("W22", 356865.99, False),
    ("W23", 382577.81, False),
    ("W24", 439692.77, False),
    ("W25", 355410.28, False),
    ("W26 (WTD)", 460472.76, True),
]
max_net = max(w[1] for w in week_data)
week_rows = []
for label, net, is_cur in week_data:
    pct_bar = round(net / max_net * 100, 1)
    week_rows.append({
        "wk_label":       label,
        "wk_net":         fmt(net),
        "wk_bar_pct":     str(pct_bar),
        "wk_bar_color":   "#F27061" if is_cur else "#C9C7FF",
        "wk_label_color": "#F27061" if is_cur else "#2b2b33",
        "wk_val_color":   "#F27061" if is_cur else "#2b2b33",
        "wk_weight":      "700" if is_cur else "400",
    })

# -- bu_rows -----------------------------------------------------------------
bu_name_map = {
    "8": "Retails",
    "10": "Vending",
    "12": "Wholesale",
    "126": "Shopee",
    "127": "Lazada",
    "128": "TikTok",
    "107": "E-Commerce",
}
bu_raw = [
    {"cls": "8",   "prev": 316515.09, "wtd": 212038.45},
    {"cls": "10",  "prev": 23848.46,  "wtd": 14687.80},
    {"cls": "12",  "prev": 0,         "wtd": 213875.51},
    {"cls": "126", "prev": 15046.73,  "wtd": 19871.00},
]
total_wtd = sum(b["wtd"] for b in bu_raw)
max_wtd   = max(b["wtd"] for b in bu_raw)
bu_rows = []
for b in bu_raw:
    wow_val = (b["wtd"] / b["prev"] - 1) if b["prev"] > 0 else None
    share = round(b["wtd"] / total_wtd * 100, 1)
    bu_rows.append({
        "bu_name":      bu_name_map.get(b["cls"], b["cls"]),
        "bu_net":       fmt(b["wtd"]),
        "bu_share":     str(share),
        "bu_wow":       pct(wow_val * 100) if wow_val is not None else "new",
        "bu_wow_color": wow_color(wow_val) if wow_val is not None else "#b5740a",
        "bu_bar_pct":   str(round(b["wtd"] / max_wtd * 100, 1)),
        "bu_bar_color": "#5551FE",
    })

# -- branch_rows (3-week trend D) -------------------------------------------
branch_raw = [
    {"loc": "176", "w2": 179788.34, "w1": 185249.47, "w0": 189879.74},
    {"loc": "174", "w2": 79937.32,  "w1": 99027.04,  "w0": 78218.60},
    {"loc": "198", "w2": 53352.31,  "w1": 43566.28,  "w0": 37341.05},
    {"loc": "172", "w2": 37712.16,  "w1": 90762.22,  "w0": 26122.43},
    {"loc": "210", "w2": 19870.94,  "w1": 9296.23,   "w0": 12282.18},
    {"loc": "197", "w2": 5794.35,   "w1": 4794.36,   "w0": 3579.42},
    {"loc": "194", "w2": 4110.25,   "w1": 1512.14,   "w0": 4594.36},
    {"loc": "196", "w2": 2012.14,   "w1": 5485.03,   "w0": 3392.50},
    # DARK stores
    {"loc": "235", "w2": 0, "w1": 0, "w0": 0, "dark": True},
    {"loc": "177", "w2": 0, "w1": 0, "w0": 0, "dark": True},
]
branch_rows = []
for b in branch_raw:
    is_dark = b.get("dark", False)
    is_wholesale_spike = b["loc"] == "172"  # W24 spike
    trend_up = b["w0"] >= b["w1"]
    flag = ""
    if is_dark:
        flag = '<span style="background:#fde8e8;color:#c43b27;font-size:10px;font-weight:600;padding:1px 6px;border-radius:9px;">DARK</span>'
    elif is_wholesale_spike:
        flag = '<span style="background:#fbeecd;color:#b5740a;font-size:10px;font-weight:600;padding:1px 6px;border-radius:9px;">WHOLESALE W24</span>'
    branch_rows.append({
        "br_name":       loc_names.get(b["loc"], b["loc"]),
        "br_w2":         fmt(b["w2"]) if b["w2"] else "—",
        "br_w1":         fmt(b["w1"]) if b["w1"] else "—",
        "br_w0":         fmt(b["w0"]) if b["w0"] else "—",
        "br_w0_color":   "#1f9d57" if trend_up and not is_dark else "#d6453a",
        "br_trend":      "▲" if trend_up and not is_dark else "▼" if not is_dark else "—",
        "br_trend_color":"#1f9d57" if trend_up and not is_dark else "#d6453a",
        "br_flag":       flag,
        "br_row_bg":     "#fff3f3" if is_dark else "#ffffff",
        "br_name_color": "#c43b27" if is_dark else "#2b2b33",
    })

# -- cat_rows ----------------------------------------------------------------
cat_total_net = 232015.87 + 1763003.74
cat_rows = [
    {
        "cat_name":     "Collectable (100–1000%)",
        "cat_skus":     "29",
        "cat_units":    "76",
        "cat_net":      fmt(232015.87),
        "cat_share":    str(round(232015.87 / cat_total_net * 100, 1)),
        "cat_asp":      "3,053",
        "cat_gp":       "36.2",
        "cat_gp_color": gp_color(36.2),
    },
    {
        "cat_name":     "Rest",
        "cat_skus":     "255",
        "cat_units":    "5,635",
        "cat_net":      fmt(1763003.74),
        "cat_share":    str(round(1763003.74 / cat_total_net * 100, 1)),
        "cat_asp":      "313",
        "cat_gp":       "43.5",
        "cat_gp_color": gp_color(43.5),
    },
]

# -- reorder_rows ------------------------------------------------------------
reorder_rows = [
    {
        "ro_name":       "Fuggler Heart Care Bear Monster Plush Keychain BB",
        "ro_w4":         "29",
        "ro_w3":         "34",
        "ro_w2":         "20",
        "ro_w1":         "21",
        "ro_w0":         "16",
        "ro_stock":      "36",
        "ro_cover":      "1.6",
        "ro_stock_color":"#c43b27",
        "ro_action":     "REORDER",
        "ro_act_bg":     "#e3f5ec",
        "ro_act_color":  "#1f9d57",
    },
]

# -- top_rows (top 20 by u2, W24+W25, retail only) ---------------------------
top20_raw = [
    # name, stock, uw1(W24), uw0(W25), u2, net, gp, gp_pct
    ("Upset Duck Status Display Duck Hipper BB",     190, 52,  64,  116, 21725, 11561, 53.2),
    ("Fuggler Alley Cat Plush Keychain BB",          103, 37,  46,   83, 32595, 16678, 51.2),
    ("Upset Duck Stop The Spiral Duck BB",           427, 43,  33,   76, 14135,  7472, 52.9),
    ("Opandee Zombie Party Series 4 BB",             544, 29,  33,   62, 28392, 13672, 48.2),
    ("Upset Duck Mini Wishlist Plush Keychain BB",   186, 19,  41,   60, 21533, 11265, 52.3),
    ("Fuggler Sassy Cuties Squad Plush Keychain BB", 134, 27,  31,   58, 24329, 13386, 55.0),
    ("Grogu Chubby Planet Series Plush Keychain BB",   5, 37,  14,   51, 18561,  9776, 52.7),
    ("Mr. Bone Agent Plush Keychain BB",             273, 23,  24,   47, 24776, 11095, 44.8),
    ("Fuggler Heart Care Bear Monster Plush Keychain BB", 36, 20, 21, 41, 16467, 7619, 46.3),
    ("Upset Duck Pocket Crazy Circus Duck Plush Keychain BB", 136, 21, 17, 38, 14916, 6160, 41.3),
    ("Sanrio Characters Sweet Style Phone Chain Mini BB", 32, 27, 10, 37,  7608,  3751, 49.3),
    ("Naruto Kittenland Plush Keychain BB",            0, 18,   2,   37,  7850,  None, None),
    ("Opandee Lucky Zombie Thirteen Orphans BB",      246, 20,  13,   33,  8635,  4350, 48.2),
    ("Cat Hug Plush Keychain BB",                    264, 18,  11,   29, 13103,  7243, 55.3),
    ("Cat Hug Figure BB",                             99, 19,   8,   27,  5021,  2760, 55.0),
    ("Disney Princess Pony Plush Keychain BB",         35, 20,   6,   26, 11028,  5099, 46.2),
    ("Panpan Mini 4th Anniversary BB",               130, 20,   5,   25, 10701,  3556, 33.2),
    ("Bearbrick Series 50 Figure BB",                911, 12,  12,   24,  4464,  2370, 53.1),
    ("Naruto Shippuden Cute Animal Sit In Party Plush Keychain BB", 114, 17, 6, 23, 11925, 5887, 49.4),
    ("Oyo Constellation Story V.2 Series Hipper BB", 136, 10,  13,   23,  3439,  1670, 48.5),
]
two_wk_days = 14
top_rows = []
for (name, stock, uw1, uw0, u2, net, gp, gp_pct) in top20_raw:
    per_day = round(u2 / two_wk_days, 1)
    top_rows.append({
        "tp_name":      name,
        "tp_stock":     fmt(stock),
        "tp_stock_color": stock_color(stock),
        "tp_w1":        str(uw1),
        "tp_w0":        str(uw0),
        "tp_w0_color":  "#1f9d57" if uw0 >= uw1 else "#d6453a",
        "tp_2wk":       str(u2),
        "tp_day":       str(per_day),
        "tp_net":       fmt(net),
        "tp_gp":        fmt(gp) if gp is not None else "—",
        "tp_gp_pct":    str(gp_pct) if gp_pct is not None else "—",
        "tp_gp_color":  gp_color(gp_pct) if gp_pct is not None else "#8a8a93",
    })

# -- arrival_rows (W22–W26 recent launches with on_hand>0) -------------------
# na_read logic: sold/recvd & on_hand-based
def arrival_read(sold, on_hand, launch_wk):
    # Simple heuristic
    if on_hand == 0: return "SOLD OUT", "#e3f5ec", "#1f9d57"
    weeks_since = 26 - launch_wk
    if weeks_since <= 1: return "JUST IN", "#eeedfe", "#5551FE"
    if on_hand < 10 and sold > on_hand * 2: return "HOT", "#fde8e8", "#c43b27"
    sell_rate = sold / max(weeks_since, 1)
    cover = on_hand / sell_rate if sell_rate > 0 else 99
    if cover > 12: return "OVERSTOCK", "#fbeecd", "#b5740a"
    if cover > 6:  return "SLOW", "#f5f5f5", "#8a8a93"
    if cover < 2:  return "HOT", "#fde8e8", "#c43b27"
    return "SELLING", "#e3f5ec", "#1f9d57"

arrival_data = [
    # (wk_label, name, recvd, sold, on_hand, launch_iso_week)
    ("W22", "Astro Boy Red Boots Samurai (Black Ed.) 200%", "—", "sold out", 0, 22),
    ("W23", "Lulu The Piggy Lucky Cat Figure BB",           "~30", 18, 12, 23),
    ("W23", "Lulu The Piggy Office Series Figure BB",       "~12", 10,  2, 23),
    ("W24", "The Powerpuff Girls Cozy Moment Plush BB",     "144",  0,  0, 24),
    ("W24", "Lollipoppi Bag Charm Plush Keychain BB",       "~131", 6, 125, 24),
    ("W25", "Seal Beans Friends Squishy BB",                "~24",  8,  0, 25),  # sold out today
    ("W26", "Shiba Macarons Squishy BB",                    "~24",  0, 24, 26),
    ("W26", "Garfield Loves Fruits Figure BB",              "—",    0,  0, 26),
    ("W26", "Garfield Magnet BB",                           "—",    0,  0, 26),
]

arrival_rows = []
for (wk, name, recvd, sold_val, oh, launch_wk) in arrival_data:
    sold_n = sold_val if isinstance(sold_val, int) else 0
    if isinstance(sold_val, str) and sold_val == "sold out":
        read, read_bg, read_color = "SOLD OUT", "#e3f5ec", "#1f9d57"
    else:
        read, read_bg, read_color = arrival_read(sold_n, oh, launch_wk)
    oh_color = "#c43b27" if oh < 10 else "#b5740a" if oh > 100 else "#2b2b33"
    arrival_rows.append({
        "na_wk":        wk,
        "na_name":      name,
        "na_recvd":     str(recvd) if recvd != "—" else "—",
        "na_sold":      str(sold_val),
        "na_onhand":    str(oh),
        "na_oh_color":  oh_color,
        "na_read":      read,
        "na_read_bg":   read_bg,
        "na_read_color":read_color,
    })

# -- po_rows (top 10 open POs by THB) ----------------------------------------
# Flag legend: OK=green, NEW=amber, OLD=amber-darker, OLD·CONSIGN=red
def po_flag_style(flag):
    if "CONSIGN" in flag or "CANCEL" in flag:
        return "#fde8e8", "#c43b27"
    if "OLD" in flag:
        return "#fbeecd", "#b5740a"
    if "NEW" in flag:
        return "#fbeecd", "#b5740a"
    return "#e3f5ec", "#1f9d57"

po_raw = [
    ("POACT251200065", "Upset Duck Status Display Duck Hipper BB",           384,  217836, "OLD"),
    ("POACT260400017", "Bearbrick Oscar The Grouch (Original Orange) 400%",   10,   40686, "NEW"),
    ("POACT260300049", "Fuggler Alley Cat Plush Keychain BB",                216,   37038, "OK"),
    ("POACT260300045", "The Powerpuff Girls Cozy Moment Plush BB",           144,   34541, "NEW"),
    ("POACT260300033", "Bearbrick Godzilla 2023 100%+400%",                    2,   33912, "NEW"),
    ("POACT251200030", "Diesel X Dolores Collaboration Figure BB",           168,   32498, "OLD"),
    ("POACT250600009", "Mimi Leisurely Elf Vinyl Plush",                      90,   32120, "OLD·CONSIGN"),
    ("POACT250600010", "Mimi Leisurely Elf Vinyl Plush",                      90,   32120, "OLD·CONSIGN"),
    ("POACT260200033", "Spiderman Brand New Day Plush Keychain BB",           96,   32075, "NEW"),
    ("POACT260500012", "Panpan Bear Cafe Stories Figure BB",                 120,   28639, "NEW"),
]
po_rows = []
for (num, name, qty, thb, flag) in po_raw:
    bg, color = po_flag_style(flag)
    po_rows.append({
        "po_name":      name,
        "po_num":       num,
        "po_qty":       fmt(qty),
        "po_value":     "&#3647;" + fmt(thb),
        "po_flag":      flag,
        "po_flag_bg":   bg,
        "po_flag_color":color,
        "po_row_bg":    "#fff8f6" if "CONSIGN" in flag else "#ffffff",
    })

# -- dead_owned_rows (top owned dead stock) ----------------------------------
# Top items not in Big Box / MNT / interco buckets
dead_owned_raw = [
    ("Bearbrick Royal Selangor × Steven Harrington (Gold) 1000%", 2, 82536),
    ("Bearbrick Royal Selangor × Steven Harrington (Silver) 1000%", 2, 82536),
    ("Bearbrick Clot Watermelon & Strawberry 1000%", 2, 74901),
    ("Flyman 23 (by Edgar Plans)", 5, 26577),
    ("Astro Boy Jiangshi Awakening 200%", 18, 6229),
    ("Astro Boy Feat. Tokidoki 200%", 21, 5220),
    ("Jelilo (Devil Fish)", 20, 5383),
    ("Jelilo (Sea Dog)", 19, 5383),
    ("Jelilo (Shark Tooth)", 19, 5383),
    ("Jelilo (Scar Face)", 20, 4970),
]
dead_owned_rows = []
for (name, oh, cost) in dead_owned_raw:
    val = oh * cost
    dead_owned_rows.append({
        "do_name":   name,
        "do_onhand": str(oh),
        "do_cost":   "&#3647;" + fmt(cost),
        "do_price":  "—",
        "do_value":  "&#3647;" + fmt(val),
    })

# -- dead_consign_rows -------------------------------------------------------
dc_consign_color = {"bg": "#e1f5ee", "color": "#0f6e56"}
dc_interco_color = {"bg": "#eeedfe", "color": "#5551FE"}

dead_consign_rows = [
    {
        "dc_tag":      "CONSIGN",
        "dc_tag_bg":   dc_consign_color["bg"],
        "dc_tag_color":dc_consign_color["color"],
        "dc_supplier": "Big Box International",
        "dc_skus":     "68",
        "dc_units":    "424",
        "dc_action":   "RETURN",
    },
    {
        "dc_tag":      "CONSIGN",
        "dc_tag_bg":   dc_consign_color["bg"],
        "dc_tag_color":dc_consign_color["color"],
        "dc_supplier": "MNT-series (V-00654)",
        "dc_skus":     "49",
        "dc_units":    "3,708",
        "dc_action":   "RETURN",
    },
    {
        "dc_tag":      "INTERCO",
        "dc_tag_bg":   dc_interco_color["bg"],
        "dc_tag_color":dc_interco_color["color"],
        "dc_supplier": "Pony/Toysinbox/Chaw/ACT TH interco",
        "dc_skus":     "267",
        "dc_units":    "3,411",
        "dc_action":   "RETURN",
    },
]

# ── SECTIONS ────────────────────────────────────────────────────────────────
sections = {
    "exec_insight": True,
    "best_today":   True,
}

# ── ASSEMBLE ─────────────────────────────────────────────────────────────────
data = {
    "scalars":  scalars,
    "repeats":  {
        "insight_rows":       insight_rows,
        "today_branch_rows":  today_branch_rows,
        "week_rows":          week_rows,
        "bu_rows":            bu_rows,
        "branch_rows":        branch_rows,
        "cat_rows":           cat_rows,
        "reorder_rows":       reorder_rows,
        "top_rows":           top_rows,
        "arrival_rows":       arrival_rows,
        "po_rows":            po_rows,
        "dead_owned_rows":    dead_owned_rows,
        "dead_consign_rows":  dead_consign_rows,
    },
    "sections": sections,
}

with open("data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("data.json written successfully.")
print(f"  Scalars: {len(scalars)} tokens")
print(f"  Repeats: {', '.join(f'{k}={len(v)}' for k,v in data['repeats'].items())}")
