import json, math

def fmt(n, decimals=0):
    if n is None: return "—"
    v = round(float(n), decimals)
    if decimals == 0:
        return f"{int(v):,}"
    return f"{v:,.{decimals}f}"

def pct(n, decimals=1):
    return f"{round(float(n)*100, decimals):+.{decimals}f}%"

def gp_color(g):
    return "#c43b27" if float(g) < 50 else "#1f7a55"

def wow_color(v):
    return "#1f9d57" if float(v) >= 0 else "#d6453a"

def wow_arrow(v):
    return "▲" if float(v) >= 0 else "▼"

def stock_color(s):
    s = float(s)
    if s < 15: return "#c43b27"
    if s > 600: return "#b5740a"
    return "#2b2b33"

# ── Scalars ────────────────────────────────────────────────────────────────────
# Query A results
retail_today  = 26103.72
retail_lw     = 30254.14   # last same-weekday (Tue Jun 16)
retail_bills  = 48
wtd_net       = 55486.84
wtd_days      = 2
day_wow       = retail_today / retail_lw - 1   # -0.1372

scalars = {
    "report_date_display": "23 Jun 2026",
    "report_weekday": "Tue",
    "iso_week": "26",
    "mode_badge": "DAILY",
    "mode_badge_color": "#F27061",
    "generated_at": "23 Jun 2026 22:07 BKK",
    "footer_cchaw": "CHAW Retailing Co., Ltd. · Internal management report · Generated by automated routine.",
    # KPI
    "day_net":      fmt(retail_today),
    "day_bills":    str(retail_bills),
    "day_ticket":   fmt(retail_today / retail_bills),
    "day_wow_pct":  f"{day_wow*100:+.1f}%",
    "day_wow_arrow": wow_arrow(day_wow),
    "day_wow_color": wow_color(day_wow),
    "day_bills_split": "48 retail bills · no wholesale today",
    "wtd_net":      fmt(wtd_net),
    "wtd_days":     str(wtd_days),
    "wtd_per_day":  fmt(wtd_net / wtd_days),
    "today_branch_note": "Westgate (ACT235) and vending: no sales posted today.",
    "best_today_list": "Upset Duck Status Display Duck Hipper (9u) · One Piece Egghead Scented (8u) · Fuggler Alley Cat (5u)",
    # Week
    "week_note": "W21 ฿755k reflects a jump — review for bulk orders. W26 is week-to-date (2 days, Mon–Tue). Net = invoices − returns; wash lines excluded.",
    # Date tokens for reorder table
    "w_minus4": "22",
    "w_minus3": "23",
    "w_minus2": "24",
    "w_minus1": "25",
    # Branch
    "br_w2_label": "W23",
    "br_w1_label": "W24",
    "br_w0_label": "W25",
    "branch_note": "Westgate (ACT235) dark — zero sales W23–W25 (3 consecutive complete weeks); check store/POS status. Warehouse HQ W24 spike (฿90,762) likely includes a wholesale or stock transfer.",
    # Category
    "cat_note": "Trailing 4 weeks (26 May – 23 Jun 2026). GP uses item average cost (THB base). Prices net of 7% VAT.",
    # Reorder
    "reorder_note": "1 item meets criteria (W25+WTD ≥ 20u, stock < 90, cover < 3×). W26 WTD is only 2 days — velocity column understates weekly run-rate.",
    # Top 20
    "top_w1_label": "W24",
    "top_w0_label": "W25",
    "top_note": "Wholesale (Siam Specialty): ฿72,439 / 309 units / 12 SKUs / 4 orders — excluded from rankings above. Retail only (entity ≠ 132/14186).",
    # PO
    "po_note": "Top items by open value; 720 total approved PO lines. FX rates used: USD ≈ 32.76 · CNY ≈ 4.8 · SGD ≈ 25.7.",
    # Dead stock
    "dead_owned_skus": "82",
    "dead_owned_value": "647,837",
    "dead_note": ("Owned: 82 SKUs / 541u / ฿647,837 (elevated vs historical 10–20 SKU calibration; "
                  "sold-exclusion filter confirmed working — no current top-20 sellers in dead set). "
                  "Big Box: 75 SKUs / 425u / ≈฿3.5M. MNT consignment: 47 SKUs / 3,548u. "
                  "Interco (Pony/Toysinbox/Chaw/ActionCity TH): 263 SKUs / 3,134u."),
}

# ── insight_rows ───────────────────────────────────────────────────────────────
insight_rows = [
    {"insight": "Today retail ฿26,104 (−13.7% vs same-weekday last week / last Tue ฿30,254). WTD W26: ฿55,487 over 2 days (~฿27,744/day)."},
    {"insight": "Retails BU leads WTD at ฿47,627 (85.8% share); Shopee ฿5,168 (9.3%); Vending ฿2,692 (4.9%). Prior full week Retails ฿316,515."},
    {"insight": "Branch leader: Siam Square One — W25 ฿189,880 (+2.5% WoW). Central Ladprao declining 3 consecutive weeks: W23 ฿53,352 → W24 ฿43,566 → W25 ฿37,341 (−30% three-week slide)."},
    {"insight": "⚠ Westgate (ACT235) recorded zero sales in W23, W24 and W25 — three consecutive full weeks dark. Verify store status and POS connectivity."},
    {"insight": "Reorder watch: Fuggler Heart Care Bear Monster (cover 2.5×, stock 49, W25 velocity 21/wk) → WATCH; monitor next week."},
    {"insight": "Dead stock: Big Box consignment 75 SKUs / 425u / ≈฿3.5M — RETURN candidate. Owned dead 82 SKUs / 541u / ฿647,837 (led by premium Bearbrick 1000% singles and Mr. Bone Christmas) — action to clear."},
]

# ── today_branch_rows ──────────────────────────────────────────────────────────
def branch_row(name, net, bills, retail_net, retail_bills, flag=""):
    ticket = fmt(retail_net / retail_bills) if retail_bills > 0 else "—"
    is_wholesale = (net - retail_net) > 1000
    bg = "#fff9f0" if is_wholesale else "#ffffff"
    color = "#2b2b33"
    pill = f'<span style="background:#e1f5ee;color:#0f6e56;font-size:10px;font-weight:600;padding:1px 6px;border-radius:9px;">WHOLESALE</span>' if is_wholesale else ""
    return {"tb_name": name, "tb_net": fmt(net), "tb_bills": str(bills),
            "tb_ticket": ticket, "tb_flag": pill, "tb_bg": bg, "tb_color": color}

today_branch_rows = [
    branch_row("Siam Square One",   13786.90, 25, 13786.90, 25),
    branch_row("Fashion Island",     5887.85, 10,  5887.85, 10),
    branch_row("Warehouse HQ",       3392.53,  6,  3392.53,  6),
    branch_row("Central Ladprao",    3036.44,  7,  3036.44,  7),
]

# ── week_rows ──────────────────────────────────────────────────────────────────
weeks_raw = [
    ("W20", 362936.34, False),
    ("W21", 755367.43, False),
    ("W22", 356865.99, False),
    ("W23", 382577.81, False),
    ("W24", 439692.77, False),
    ("W25", 355410.28, False),
    ("W26 (WTD)", 55486.84, True),
]
max_wk = max(w[1] for w in weeks_raw)
week_rows = []
for label, net, is_cur in weeks_raw:
    week_rows.append({
        "wk_label":      label,
        "wk_net":        fmt(net),
        "wk_bar_pct":    str(round(net / max_wk * 100, 1)),
        "wk_bar_color":  "#F27061" if is_cur else "#C9C7FF",
        "wk_label_color":"#5551FE" if is_cur else "#2b2b33",
        "wk_val_color":  "#5551FE" if is_cur else "#2b2b33",
        "wk_weight":     "600" if is_cur else "400",
    })

# ── bu_rows ────────────────────────────────────────────────────────────────────
bu_raw = [
    (8,   "Retails",   316515.09, 47627.03),
    (126, "Shopee",     15046.73,  5168.23),
    (10,  "Vending",    23848.46,  2691.58),
]
total_wtd_bu = sum(b[3] for b in bu_raw)
max_wtd_bu   = max(b[3] for b in bu_raw)
bu_rows = []
for cls, name, prev, wtd in bu_raw:
    share = wtd / total_wtd_bu * 100
    wow   = wtd / prev - 1
    bu_rows.append({
        "bu_name":      name,
        "bu_net":       fmt(wtd),
        "bu_bar_pct":   str(round(wtd / max_wtd_bu * 100, 1)),
        "bu_bar_color": "#5551FE",
        "bu_share":     f"{share:.1f}",
        "bu_wow":       f"{wow*100:+.1f}%",
        "bu_wow_color": wow_color(wow),
    })

# ── branch_rows ────────────────────────────────────────────────────────────────
branches_raw = [
    ("Siam Square One",     176, 179788.34, 185249.47, 189879.74, ""),
    ("Fashion Island",      174,  79937.32,  99027.04,  78218.60, ""),
    ("Central Ladprao",     198,  53352.31,  43566.28,  37341.05, ""),
    ("Warehouse HQ",        172,  37712.16,  90762.22,  26122.43, ""),
    ("IconSiam 6F ⚙",       210,  19870.94,   9296.23,  12282.18, ""),
    ("Bangkapi 1 ⚙",        196,   2012.14,   5485.03,   3392.50, ""),
    ("Bangkapi 2 ⚙",        197,   5794.35,   4794.36,   3579.42, ""),
    ("Rama 9 ⚙",            194,   4110.25,   1512.14,   4594.36, ""),
    ("Westgate",            235,   0.0,         0.0,       0.0,   "DARK"),
]
branch_rows = []
for name, loc, w2, w1, w0, flag in sorted(branches_raw, key=lambda x: x[4], reverse=True):
    is_dark = flag == "DARK"
    trend_up = w0 >= w1
    br_w0_color = "#1f9d57" if trend_up and not is_dark else "#d6453a"
    trend_sym   = "▲" if trend_up and not is_dark else ("— " if is_dark else "▼")
    trend_color = "#1f9d57" if trend_up and not is_dark else "#d6453a"
    br_name_color = "#c43b27" if is_dark else "#2b2b33"
    br_row_bg   = "#fff5f5" if is_dark else "#ffffff"
    flag_pill = ""
    if is_dark:
        flag_pill = '<span style="background:#fde8e8;color:#c43b27;font-size:10px;font-weight:600;padding:1px 6px;border-radius:9px;">DARK</span>'
    branch_rows.append({
        "br_name":       name,
        "br_w2":         fmt(w2) if w2 > 0 else "—",
        "br_w1":         fmt(w1) if w1 > 0 else "—",
        "br_w0":         fmt(w0) if w0 > 0 else "—",
        "br_trend":      trend_sym,
        "br_trend_color":trend_color,
        "br_w0_color":   br_w0_color,
        "br_name_color": br_name_color,
        "br_row_bg":     br_row_bg,
        "br_flag":       flag_pill,
    })

# ── cat_rows ───────────────────────────────────────────────────────────────────
total_cat_net = 155052.33 + 1404895.43
cat_rows = [
    {"cat_name": "Collectable (100–1000%)", "cat_skus": "24", "cat_units": "45",
     "cat_net": fmt(155052.33), "cat_share": f"{155052.33/total_cat_net*100:.1f}",
     "cat_asp": fmt(3446), "cat_gp": "42.6", "cat_gp_color": gp_color(42.6)},
    {"cat_name": "Rest",                    "cat_skus": "227", "cat_units": "4,569",
     "cat_net": fmt(1404895.43), "cat_share": f"{1404895.43/total_cat_net*100:.1f}",
     "cat_asp": fmt(307), "cat_gp": "42.1", "cat_gp_color": gp_color(42.1)},
]

# ── reorder_rows ───────────────────────────────────────────────────────────────
reorder_rows = [
    {"ro_name": "Fuggler Heart Care Bear Monster Plush Keychain Blind Box",
     "ro_w4": "29", "ro_w3": "34", "ro_w2": "20", "ro_w1": "21", "ro_w0": "3",
     "ro_stock": "49", "ro_cover": "2.5×",
     "ro_stock_color": "#2b2b33",
     "ro_action": "WATCH", "ro_act_bg": "#fbeecd", "ro_act_color": "#b5740a"},
]

# ── top_rows ───────────────────────────────────────────────────────────────────
top20_data = [
    # name, stock, uw1(W24), uw0(W25), u2, net, gp
    ("Upset Duck Status Display Duck Hipper Blind Box", 274, 52, 64, 116, 21725.08, 11559.24),
    ("Fuggler Alley Cat Plush Keychain Blind Box",      147, 37, 46,  83, 32595.10, 16655.26),
    ("Upset Duck Stop The Spiral Duck Blind Box",       452, 43, 33,  76, 14134.50,  7471.91),
    ("Opandee Zombie Party Series 4 Figures Blind Box", 549, 29, 33,  62, 28392.44, 13672.14),
    ("Upset Duck Mini Wishlist Plush Keychain Blind Box",211,19, 41,  60, 21532.70, 11265.21),
    ("Fuggler Sassy Cuties Squad Plush Keychain Blind Box",158,27,31, 58, 24329.40, 13377.60),
    ("Grogu Chubby Planet Series Plush Keychain Blind Box", 5, 37,14, 51, 18560.74,  9775.79),
    ("Mr. Bone Agent Plush Keychain Blind Box",         287, 23, 24,  47, 24775.74, 11094.53),
    ("Fuggler Heart Care Bear Monster Plush Keychain Blind Box", 49, 20, 21, 41, 16467.18, 7619.20),
    ("Upset Duck Pocket Crazy Circus Duck Plush Keychain Blind Box",170,21,17,38,14915.78, 6158.32),
    ("Sanrio Characters Sweet Style Phone Chain Mini Blind Box", 50, 27, 10, 37,  7607.54,  3751.17),
    ("Cat Hug Plush Keychain Blind Box",                279, 18, 11,  29, 13102.86,  7242.59),
    ("Qmsv Strike & Destiny Gundam Figure Blind Box",    73, 10, 17,  27, 12299.12,  5361.71),
    ("Cat Hug Figure Blind Box",                        105, 19,  8,  27,  5021.47,  2760.24),
    ("Disney Princess Pony Plush Keychain Blind Box",    45, 20,  6,  26, 11028.02,  5099.51),
    ("Panpan Mini 4th Anniversary Blind Box",           131, 20,  5,  25, 10700.93,  3553.47),
    ("Bearbrick Series 50 Figure Blind Box",            916, 12, 12,  24,  4463.52,  2369.97),
    ("Sanrio Characters Love Bow Phone Chain Mini Blind Box", 67, 15, 8, 23,  8168.22,  4625.17),
    ("Naruto Shippuden Cute Animal Sit In Party Plush Keychain Blind Box",140,17, 6,23,11925.25,5887.24),
    ("Oyo Constellation Story V.2 Series Hipper Blind Box",153,10,13, 23,  3439.21,  1669.78),
]
TWO_WK_DAYS = 14
top_rows = []
for name, stock, uw1, uw0, u2, net, gp in top20_data:
    gp_pct = gp / net * 100
    tp_w0_color = "#1f9d57" if uw0 >= uw1 else "#d6453a"
    top_rows.append({
        "tp_name":      name,
        "tp_stock":     fmt(stock),
        "tp_stock_color": stock_color(stock),
        "tp_w1":        str(uw1),
        "tp_w0":        str(uw0),
        "tp_w0_color":  tp_w0_color,
        "tp_2wk":       str(u2),
        "tp_day":       f"{u2/TWO_WK_DAYS:.1f}",
        "tp_net":       fmt(net),
        "tp_gp":        fmt(gp),
        "tp_gp_pct":    f"{gp_pct:.1f}",
        "tp_gp_color":  gp_color(gp_pct),
    })

# ── arrival_rows ───────────────────────────────────────────────────────────────
def arrival_read_badge(sold, stock, first_sale_wk):
    # HOT: very fast selling relative to stock
    ratio = sold / max(stock, 1)
    if ratio > 10 or (sold > 50 and stock < 20): return ("HOT",  "#1f9d57", "#ffffff")
    if ratio > 1.5 or sold > 30:                  return ("SELLING", "#e3f5ec", "#1f7a55")
    if sold < 5:                                   return ("JUST IN", "#E6E5FF", "#5551FE")
    return ("SELLING", "#e3f5ec", "#1f7a55")

def oh_color(stock):
    return "#c43b27" if stock < 10 else "#2b2b33"

arrival_data = [
    # wk label, name, recvd≈, sold, stock
    ("W23", "Grogu Chubby Planet Series Plush Keychain Blind Box",       72,  67,  5),
    ("W21", "Upset Duck Mini Wishlist Plush Keychain Blind Box",        428, 217, 211),
    ("W22", "Fuggler Sassy Cuties Squad Plush Keychain Blind Box",      256,  98, 158),
    ("W23", "Sanrio Characters Sweet Style Phone Chain Mini Blind Box",  96,  46,  50),
    ("W23", "Sanrio Characters Love Bow Phone Chain Mini Blind Box",     96,  29,  67),
    ("W24", "Naruto Kittenland Plush Keychain Blind Box",                24,  20,   4),
    ("W24", "Lulu The Piggy Lucky Cat Figure Blind Box",                 32,  19,  13),
    ("W25", "Lollipoppi Bag Charm Plush Keychain Blind Box",            166,  11, 155),
    ("W23", "Lulu The Piggy Office Series Figure Blind Box",            16,  14,   2),
    ("W24", "Uran Jiangshi 200%",                                         8,   1,   7),
]
arrival_rows = []
for wk, name, recvd, sold, stock in arrival_data:
    badge, bg, color = arrival_read_badge(sold, stock, wk)
    arrival_rows.append({
        "na_wk":      wk,
        "na_name":    name,
        "na_recvd":   str(recvd),
        "na_sold":    str(sold),
        "na_onhand":  str(stock),
        "na_oh_color": oh_color(stock),
        "na_read":    badge,
        "na_read_bg": bg,
        "na_read_color": color,
    })

# ── po_rows ────────────────────────────────────────────────────────────────────
def po_flag_badge(flag_type):
    if flag_type == "OK":    return ("#e3f5ec", "#1f9d57", "OK",  "#ffffff")
    if flag_type == "NEW":   return ("#E6E5FF", "#5551FE", "NEW", "#ffffff")
    if flag_type == "OLD":   return ("#fbeecd", "#b5740a", "OLD", "#ffffff")
    if flag_type == "ZERO":  return ("#fde8e8", "#c43b27", "0 SOLD", "#ffffff")
    return ("#e3f5ec", "#1f9d57", "OK", "#ffffff")

po_data = [
    ("Upset Duck Status Display Duck Hipper Blind Box",       "POACT251200065", 384, 217836, "OK"),
    ("Sup. Pro. Manekineko Figure Blind Box",                 "POACT260600025", 280,  61576, "NEW"),
    ("Bearbrick Oscar The Grouch (Orange) 100%",             "POACT260400017",  10,  40686, "OK"),
    ("Fuggler Alley Cat Plush Keychain Blind Box",            "POACT260300049", 216,  37038, "OK"),
    ("The Powerpuff Girls Cozy Moment Plush Keychain",        "POACT260300045", 144,  34541, "NEW"),
    ("Bearbrick Godzilla 2023 From Godzilla Minus One 100%", "POACT260300033",   2,  33912, "OK"),
    ("Diesel X Dolores Collaboration Figure Blind Box",       "POACT251200030", 168,  32498, "OK"),
    ("Bearbrick Oscar The Grouch (Orange) 400%",             "POACT260300034",   8,  32320, "OK"),
    ("Mimi Leisurely Elf Vinyl Plush",                        "POACT250600009",  90,  32120, "OLD"),
    ("Mimi Leisurely Elf Vinyl Plush",                        "POACT250600010",  90,  32120, "OLD"),
    ("Stitch X Toy Story Plush Keychain Blind Box",          "POACT260200033",  96,  32075, "NEW"),
    ("Spiderman Brand New Day Plush Keychain Blind Box",     "POACT260200033",  96,  32075, "NEW"),
    ("Fools Garden Tomato Soup Figure Blind Box",            "POACT260600025", 144,  31668, "NEW"),
    ("Bearbrick × Van Gogh Museum Potato Eaters 100%",       "POACT260400017",  10,  29582, "OK"),
    ("Panpan Bear Cafe Stories Figure Blind Box",            "POACT260500012", 120,  28639, "NEW"),
]
po_rows = []
for name, po_num, qty, thb, flag_type in po_data:
    bg, color, label, txt = po_flag_badge(flag_type)
    row_bg = "#fffaf0" if flag_type == "OLD" else "#ffffff"
    po_rows.append({
        "po_name":      name,
        "po_num":       po_num,
        "po_qty":       fmt(qty),
        "po_value":     f"฿{fmt(thb)}",
        "po_flag":      label,
        "po_flag_bg":   bg,
        "po_flag_color":color,
        "po_row_bg":    row_bg,
    })

# ── dead_owned_rows ────────────────────────────────────────────────────────────
owned_data = [
    ("Bearbrick Rilakkuma With Crown 1000%",    1,  67450, 67450),
    ("Mr. Bone Christmas 200%",                 8,   7646, 61168),
    ("Bearbrick Tom And Jerry Costume 1000%",   1,  41500, 41500),
    ("Bearbrick MK85 Chrome",                   1,  29500, 29500),
    ("Bearbrick Crayon Shinchan 1000%",          1,  29000, 29000),
    ("Bearbrick Nike Tech Fleece N98 1000%",     1,  28500, 28500),
    ("Bearbrick Snoopy Astronaut 1000%",         1,  26500, 26500),
    ("Sanrio Family & Friends Series Plush",    96,    268, 25707),
    ("Hitohatausagi",                            1,  20828, 20828),
    ("Bearbrick The Batman",                     1,  18500, 18500),
    ("Bearbrick Naga Limited Thai",              1,  17000, 17000),
    ("Mofusand Bread Cat Plush Keychain Blind Box",120, 106, 12712),
]
dead_owned_rows = []
for name, oh, cost, val in owned_data:
    dead_owned_rows.append({
        "do_name":    name,
        "do_onhand":  str(oh),
        "do_cost":    fmt(cost),
        "do_price":   "—",
        "do_value":   fmt(val),
    })

# ── dead_consign_rows ──────────────────────────────────────────────────────────
dead_consign_rows = [
    {"dc_tag": "CONSIGN", "dc_tag_bg": "#e1f5ee", "dc_tag_color": "#0f6e56",
     "dc_supplier": "Big Box International",
     "dc_skus": "75", "dc_units": "425", "dc_action": "RETURN"},
    {"dc_tag": "CONSIGN", "dc_tag_bg": "#e1f5ee", "dc_tag_color": "#0f6e56",
     "dc_supplier": "ACTIONCITY PTE (MNT series)",
     "dc_skus": "47", "dc_units": "3,548", "dc_action": "RETURN"},
    {"dc_tag": "INTERCO", "dc_tag_bg": "#eeedfe", "dc_tag_color": "#5551FE",
     "dc_supplier": "Pony on Wheel / Toysinbox / Chaw / ActionCity TH",
     "dc_skus": "263", "dc_units": "3,134", "dc_action": "RETURN"},
]

# ── Assemble ───────────────────────────────────────────────────────────────────
data = {
    "scalars": scalars,
    "repeats": {
        "insight_rows":      insight_rows,
        "today_branch_rows": today_branch_rows,
        "week_rows":         week_rows,
        "bu_rows":           bu_rows,
        "branch_rows":       branch_rows,
        "cat_rows":          cat_rows,
        "reorder_rows":      reorder_rows,
        "top_rows":          top_rows,
        "arrival_rows":      arrival_rows,
        "po_rows":           po_rows,
        "dead_owned_rows":   dead_owned_rows,
        "dead_consign_rows": dead_consign_rows,
    },
    "sections": {
        "exec_insight": True,
        "best_today":   True,
    }
}

with open("data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("data.json written:", len(json.dumps(data)), "chars")
