import json, datetime

# ─── dates ───────────────────────────────────────────────────────────────────
report_date_display = "20 Jun 2026"
report_weekday      = "Sat"
iso_week            = 25
wtd_days            = 6
w_minus1,w_minus2,w_minus3,w_minus4 = 24,23,22,21
generated_at        = "2026-06-20 22:04 (Asia/Bangkok)"
mode_badge          = "DAILY"
mode_badge_color    = "#F27061"

# ─── scalars ─────────────────────────────────────────────────────────────────
# Query A: today retail vs same day last week
day_net_raw   = 83223.77
day_net       = "83,224"
day_bills     = "110"
day_units     = "176"
day_ticket    = "757"
last_sat_net  = 68341.0
day_wow_raw   = (day_net_raw / last_sat_net) - 1        # +0.2178
day_wow_pct   = f"+{day_wow_raw*100:.1f}%"              # +21.8%
day_wow_color = "#1f9d57"
day_wow_arrow = "▲"
day_bills_split = "all retail · no wholesale today"
wtd_net_raw   = 291758.02
wtd_net       = "291,758"
wtd_per_day   = f"{int(wtd_net_raw/wtd_days):,}"        # 48,626

# Best sellers today
best_today_list = (
  "Upset Duck Status Display Duck (16) · "
  "Opandee Zombie Party 4 (14) · "
  "Upset Duck Mini Wishlist (10) · "
  "Upset Duck Born This Way V.1 (11) · "
  "Upset Duck X Care Bears Neon (7) · "
  "Grogu Chubby Planet (6) · "
  "Maomaomao Thief (5) · Fuggler Sassy Cuties (5) · Mr. Bone Agent (5)"
)

# Week-by-week note
week_note = (
  "W21 includes a ฿72k wholesale order to Warehouse HQ location — "
  "retail-only net for W21 is lower. W25 is week-to-date (Sat close, 6 of 7 days)."
)

# BU
bu_wtd_total = 263765 + 16638 + 11355 + 0   # = 291,758
# BU WoW note: WTD 6d vs W24 7d — per-day rates show Retails ≈−23%, Shopee ≈−32%

# Branch section labels
br_w2_label, br_w1_label, br_w0_label = "W22", "W23", "W24"

# Category note
cat_note = (
  "Trailing 4 weeks. GP% uses item average cost (THB). "
  "Both categories below 50% — cost structure review recommended."
)

# Top movers labels
top_w1_label, top_w0_label = "W23", "W24"

# Wholesale note
top_note = (
  "Wholesale (Siam Specialty, W23+W24): ฿72,439 / 309 u across 12 SKUs "
  "(4 orders) — excluded from ranking above."
)

# Reorder note
reorder_note = (
  "Cover = on-hand ÷ 4-wk retail avg (W22–W25). "
  "Velocity filter: recent 2 weeks ≥ 10 units & cover < 3."
)

# Branch note
branch_note = (
  "W22 Liberty/HQ shows negative (฿8.2k return booked that week). "
  "Westgate (235) and ActionCityHQ vending (347) are dark — zero sales for 2 full weeks."
)

# Today branch note
today_branch_note = "E-Commerce (177) and Westgate (235): no sales posted today."

# Dead stock note
dead_note = (
  "Dead = zero retail sales since 23 May 2026. "
  "Consignment/interco items: arrange return with respective supplier. "
  "Owned items: promote or bundle to clear."
)

# PO note
po_note = (
  "Approved POs only. Open qty = ordered − received. "
  "FX converted at PO exchange rate. Some large POs may still be in transit."
)

# footer
footer_cchaw = "CHAW Retailing Co., Ltd. · Internal management report · Generated by automated routine."

# ─── REPEAT rows ─────────────────────────────────────────────────────────────

# insight_rows (3-5 bullets)
insight_rows = [
  {"insight": f"Today (Sat 20 Jun): retail net ฿83,224 across 110 bills, avg ticket ฿757 — +21.8% vs same Saturday last week (฿68,341); WTD W25 = ฿291,758 over 6 days (฿48,626/day)."},
  {"insight": f"BU mix WTD: Retails dominates at 90.4% (฿263,765); Vending 5.7% (฿16,638); Shopee 3.9% (฿11,355). TikTok posted ฿0 WTD (฿2,000 in W24 — check channel)."},
  {"insight": f"Branch leaders today: Siam Square One ฿54,915 (60 bills), Fashion Island ฿20,164 (34 bills). Central Ladprao ฿43,566 in W24 but declining 3-week trend (W22 ฿61,488 → W24 ฿43,566, −29%)."},
  {"insight": f"⚠ Westgate (235) dark — zero sales for 2 consecutive full weeks (W23 + W24). Check store status / POS feed."},
  {"insight": f"Reorder urgent: Grogu Chubby Planet (stock 6u, avg 16.5u/wk, 0.4 weeks cover). Disney Princess Pony (stock 39u, 2.2 weeks cover). Naruto Kittenland (stock 5u, 1.1 weeks cover)."},
  {"insight": f"Dead stock: Big Box consignment 427 units (฿3.6M), MNT 3,481 units (฿1.0M), Interco 2,786 units (฿1.4M) — all returnable. Arrange pickups to free shelf space."},
]

# today_branch_rows
loc_name = {
  "172": "Liberty / Warehouse HQ",
  "174": "Fashion Island",
  "176": "Siam Square One",
  "194": "Vending Rama 9 ⚙",
  "196": "Vending Bangkapi 1 ⚙",
  "197": "Vending Bangkapi 2 ⚙",
  "198": "Central Ladprao",
  "210": "Vending IconSiam 6F ⚙",
  "235": "ACT Westgate",
  "347": "ActionCityHQ Vending ⚙",
  "177": "E-Commerce",
}
today_branch_data = [
  {"loc":"176","net":54915.40,"bills":60,"retail_net":54915.40,"retail_bills":60},
  {"loc":"174","net":20164.45,"bills":34,"retail_net":20164.45,"retail_bills":34},
  {"loc":"198","net":7527.10, "bills":15,"retail_net":7527.10, "retail_bills":15},
  {"loc":"172","net":616.82,  "bills":1, "retail_net":616.82,  "retail_bills":1},
]
today_branch_rows = []
for r in today_branch_data:
  ticket = round(r["retail_net"]/r["retail_bills"]) if r["retail_bills"] else 0
  today_branch_rows.append({
    "tb_name":   loc_name[r["loc"]],
    "tb_net":    f"{r['net']:,.0f}",
    "tb_bills":  str(r["bills"]),
    "tb_ticket": f"{ticket:,}",
    "tb_flag":   "",
    "tb_bg":     "#ffffff",
    "tb_color":  "#2b2b33",
  })

# week_rows
wk_raw = [
  ("W19","2026-19",468288,"#C9C7FF","normal"),
  ("W20","2026-20",362936,"#C9C7FF","normal"),
  ("W21","2026-21",755367,"#C9C7FF","normal"),
  ("W22","2026-22",356866,"#C9C7FF","normal"),
  ("W23","2026-23",382578,"#C9C7FF","normal"),
  ("W24","2026-24",439693,"#C9C7FF","normal"),
  (f"W{iso_week} (WTD)","2026-25",int(wtd_net_raw),"#F27061","current"),
]
max_net = max(r[2] for r in wk_raw)
week_rows = []
for lbl,_,net,color,wtype in wk_raw:
  bar_pct = round(net/max_net*100)
  week_rows.append({
    "wk_label":       lbl,
    "wk_label_color": "#F27061" if wtype=="current" else "#5b5547",
    "wk_weight":      "700" if wtype=="current" else "400",
    "wk_bar_color":   color,
    "wk_bar_pct":     str(bar_pct),
    "wk_net":         f"{net:,}",
    "wk_val_color":   "#F27061" if wtype=="current" else "#2b2b33",
  })

# bu_rows
bu_map = {"8":"Retails","10":"Vending","126":"Shopee","127":"Lazada","128":"TikTok","107":"E-Com","12":"Wholesale"}
bu_raw = [
  ("8",  400674, 263765),
  ("10",  21088,  16638),
  ("126", 15931,  11355),
  ("128",  2000,      0),
]
wtd_total_bu = sum(r[2] for r in bu_raw)
prev_total_bu = sum(r[1] for r in bu_raw)
bu_rows = []
for cls,prev,wtd in bu_raw:
  share = round(100*wtd/wtd_total_bu,1) if wtd_total_bu else 0
  wow   = round((wtd/prev-1)*100,1) if prev else 0
  wow_s = f"+{wow}%" if wow>=0 else f"{wow}%"
  bar_pct = round(100*wtd/max(r[2] for r in bu_raw),0) if max(r[2] for r in bu_raw)>0 else 0
  bu_rows.append({
    "bu_name":     bu_map.get(cls, f"CLS{cls}"),
    "bu_bar_color":"#5551FE",
    "bu_bar_pct":  str(int(bar_pct)),
    "bu_net":      f"{wtd:,}",
    "bu_share":    str(share),
    "bu_wow":      wow_s,
    "bu_wow_color":"#1f9d57" if wow>=0 else "#d6453a",
  })

# branch_rows (3-week trend D)
branch_raw = [
  ("172","Liberty / HQ",     -8205, 37712, 90762),
  ("174","Fashion Island",   75474, 79937, 99027),
  ("176","Siam Square One", 172795,179788,185249),
  ("194","Vending Rama 9 ⚙",  4418,  4110,  1512),
  ("196","Vending Bangkapi1⚙",2811,  2012,  5485),
  ("197","Vending Bangkapi2⚙",4231,  5794,  4794),
  ("198","Central Ladprao",  61488, 53352, 43566),
  ("210","Vending IconSiam⚙",16654, 19871,  9296),
  ("235","ACT Westgate",     26807,     0,     0),
  ("347","ActionCityHQ⚙",     393,     0,     0),
]
branch_rows = []
for loc,nm,w2,w1,w0 in branch_raw:
  dark = (w0==0 and (w1>0 or w2>0))
  flag = "🔴 DARK" if dark else ""
  trend_up = w0 >= w1
  trend_sym = "▲" if trend_up else "▼"
  trend_color = "#1f9d57" if trend_up else "#d6453a"
  w0_color = "#1f9d57" if trend_up else "#d6453a"
  branch_rows.append({
    "br_name":       nm,
    "br_name_color": "#d6453a" if dark else "#2b2b33",
    "br_w2":         f"{w2:,}" if w2!=0 else "—",
    "br_w1":         f"{w1:,}" if w1!=0 else "—",
    "br_w0":         f"{w0:,}" if w0!=0 else "—",
    "br_w0_color":   w0_color,
    "br_trend":      trend_sym,
    "br_trend_color":trend_color,
    "br_flag":       flag,
    "br_row_bg":     "#fff4f4" if dark else "#ffffff",
  })

# cat_rows
cat_rows = [
  {"cat_name":"Collectable","cat_skus":"25","cat_units":"97","cat_net":"256,754",
   "cat_share":"11.5","cat_asp":"2,647","cat_gp":"46.1","cat_gp_color":"#c43b27"},
  {"cat_name":"Rest","cat_skus":"256","cat_units":"6,619","cat_net":"1,969,508",
   "cat_share":"88.5","cat_asp":"298","cat_gp":"41.0","cat_gp_color":"#c43b27"},
]

# reorder_rows — items with cover<3, recent velocity high
reorder_data = [
  # name, w4, w3, w2, w1, w0, stock, cover, action
  ("Grogu Chubby Planet Series Plush Keychain",     0,  0,16,37,13,  6,  0.4,"REORDER↑"),
  ("Naruto Kittenland Plush Keychain Blind Box",    0,  0, 0,18, 1,  5,  1.1,"REORDER"),
  ("Disney Princess Pony Plush Keychain",          17, 26,20,20, 6, 39,  2.2,"REORDER"),
  ("A Day In The Life (Bikini Bottom) Plush KB",   13, 28,10, 8, 7, 29,  2.2,"REORDER"),
  ("Upset Duck X Care Bears Neon Sweetheart",       8,  7,21, 6,14, 47,  2.9,"SMALL BUY"),
]
reorder_rows = []
action_colors = {
  "REORDER↑": ("#e3f5ec","#1f7a55"),
  "REORDER":  ("#e3f5ec","#1f7a55"),
  "SMALL BUY":("#fbeecd","#b5740a"),
  "WATCH":    ("#fbeecd","#b5740a"),
}
for nm,w4,w3,w2,w1,w0,stock,cover,action in reorder_data:
  bg,fg = action_colors.get(action,("#f0f0f0","#555"))
  stock_color = "#c43b27" if stock < 15 else "#b5740a" if stock < 50 else "#2b2b33"
  reorder_rows.append({
    "ro_name":       nm[:50],
    "ro_w4":         str(w4) if w4 else "—",
    "ro_w3":         str(w3) if w3 else "—",
    "ro_w2":         str(w2) if w2 else "—",
    "ro_w1":         str(w1) if w1 else "—",
    "ro_w0":         str(w0) if w0 else "—",
    "ro_stock":      str(stock),
    "ro_cover":      f"{cover:.1f}w",
    "ro_action":     action,
    "ro_act_bg":     bg,
    "ro_act_color":  fg,
    "ro_stock_color":stock_color,
  })

# top_rows (top 20 by 2-week retail units W23+W24)
stock_map = {
  "Upset Duck Status Display Duck Hipper Blind Box":302,
  "Fuggler Alley Cat Plush Keychain Blind Box":166,
  "Opandee Zombie Party Series 4 Figures Blind Box":560,
  "Upset Duck Stop The Spiral Duck Blind Box":469,
  "Upset Duck Mini Wishlist Plush Keychain Blind Box":250,
  "Fuggler Heart Care Bear Monster Plush Keychain Blind Box":55,
  "Grogu Chubby Planet Series Plush Keychain Blind Box":6,
  "Fuggler Sassy Cuties Squad Plush Keychain Blind Box":54,
  "Mr. Bone Agent Plush Keychain Blind Box":301,
  "Cat Hug Plush Keychain Blind Box":282,
  "Disney Princess Pony Plush Keychain Blind Box":39,
  "Cat Hug Figure Blind Box":105,
  "Panpan Mini 4th Anniversary Blind Box":132,
  "Mr. Bone Strange Alliance Mini 3.0 Figure Blind Box":74,
  "Qmsv Strike & Destiny Gundam Figure Blind Box":80,
  "Sanrio Characters Sweet Style Phone Chain Mini Blind Box":55,
  "Fuggler Baby Pinkles Series Plush Keychain Blind Box":363,
  "Naruto Shippuden Cute Animal Sit In Party Plush Keychain Blind Box":151,
  "Oyo Constellation Story V.2 Series Hipper Blind Box":154,
  "Upset Duck Pocket Crazy Circus Duck Plush Keychain Blind Box":176,
}
top20_raw = [
  ("Upset Duck Status Display Duck Hipper Blind Box",124,72,52,23288.62,12420.53),
  ("Fuggler Alley Cat Plush Keychain Blind Box",99,62,37,38950.23,19940.23),
  ("Opandee Zombie Party Series 4 Figures Blind Box",82,53,29,37859.67,18391.83),
  ("Upset Duck Stop The Spiral Duck Blind Box",77,34,43,14320.49,7570.84),
  ("Upset Duck Mini Wishlist Plush Keychain Blind Box",70,51,19,25420.55,13441.82),
  ("Fuggler Heart Care Bear Monster Plush Keychain Blind Box",54,34,20,21719.49,10066.04),
  ("Grogu Chubby Planet Series Plush Keychain Blind Box",53,16,37,18915.88,9786.45),
  ("Fuggler Sassy Cuties Squad Plush Keychain Blind Box",51,24,27,21385.48,11808.39),
  ("Mr. Bone Agent Plush Keychain Blind Box",46,23,23,24158.92,10768.33),
  ("Cat Hug Plush Keychain Blind Box",41,23,18,18486.06,10200.84),
  ("Disney Princess Pony Plush Keychain Blind Box",40,20,20,16915.86,7793.88),
  ("Cat Hug Figure Blind Box",38,19,19,7039.36,3856.88),
  ("Panpan Mini 4th Anniversary Blind Box",37,17,20,15841.12,5259.39),
  ("Mr. Bone Strange Alliance Mini 3.0 Figure Blind Box",34,25,9,14299.05,6560.81),
  ("Qmsv Strike & Destiny Gundam Figure Blind Box",34,24,10,15439.31,6703.33),
  ("Sanrio Characters Sweet Style Phone Chain Mini Blind Box",33,6,27,6723.41,3283.93),
  ("Fuggler Baby Pinkles Series Plush Keychain Blind Box",31,15,16,11009.34,6165.86),
  ("Naruto Shippuden Cute Animal Sit In Party Plush Keychain Blind Box",30,13,17,15523.39,7648.23),
  ("Oyo Constellation Story V.2 Series Hipper Blind Box",30,20,10,4485.94,2177.99),
  ("Upset Duck Pocket Crazy Circus Duck Plush Keychain Blind Box",30,9,21,11775.63,4861.66),
]
two_wk_days = 14
top_rows = []
for nm,u2,uw1,uw0,net,gp in top20_raw:
  gp_pct = round(100*gp/net,1) if net else 0
  perday = round(u2/two_wk_days,1)
  stk = stock_map.get(nm, 0)
  stk_color = "#c43b27" if stk<15 else "#b5740a" if stk<50 else "#2b2b33"
  gp_color  = "#c43b27" if gp_pct<50 else "#1f7a55"
  w0_color  = "#1f9d57" if uw0>=uw1 else "#d6453a"
  top_rows.append({
    "tp_name":      nm[:52],
    "tp_stock":     str(stk),
    "tp_stock_color":stk_color,
    "tp_w1":        str(uw1),
    "tp_w0":        str(uw0),
    "tp_w0_color":  w0_color,
    "tp_2wk":       str(u2),
    "tp_day":       str(perday),
    "tp_net":       f"{net:,.0f}",
    "tp_gp":        f"{gp:,.0f}",
    "tp_gp_pct":    str(gp_pct),
    "tp_gp_color":  gp_color,
  })

# arrival_rows — not queried this run, omit section
arrival_rows = []

# po_rows (top 10 open POs by THB value)
po_raw = [
  ("POACT251200065","Upset Duck Status Display Duck Hipper BB",  384, 217836, 13154),
  ("POACT251200030","Diesel X Dolores Collaboration Figure BB",  168,  32498,  5735),
  ("POACT250600009","Mimi Leisurely Elf Vinyl Plush",            90,  32120,  5735),
  ("POACT250600010","Mimi Leisurely Elf Vinyl Plush",            90,  32120,  5735),
  ("POACT250600020","Chaosbaby Bright Arbiter",                    5,  24869,  5735),
  ("POACT250700030","Bob Retro Replay Blind Box",                 72,  24840, 14208),
  ("POACT250600009","The Mischievous Cat Lucifer Series BB",     90,  21970,  5735),
  ("POACT250600010","The Mischievous Cat Lucifer Series BB",     90,  21970,  5735),
  ("POACT250800030","Evangelion Vol.1 Figure Blind Box",         72,  18632, 16791),
  ("POACT250700031","Bearbrick 50 (various)",                    10,  18393, 16791),
]
interco_vendors = {5735,3655,43623,12380}
po_rows = []
for tranid,nm,qty,thb,vnd in po_raw:
  if vnd in interco_vendors:
    flag,flag_bg,flag_color = "INTERCO","#eeedfe","#5551FE"
  else:
    flag,flag_bg,flag_color = "OK","#e3f5ec","#1f7a55"
  po_rows.append({
    "po_name":       nm[:48],
    "po_num":        tranid,
    "po_qty":        str(qty),
    "po_value":      f"฿{thb:,}",
    "po_flag":       flag,
    "po_flag_bg":    flag_bg,
    "po_flag_color": flag_color,
    "po_row_bg":     "#ffffff",
  })

# dead_owned_rows (top 8 by on-hand, owned not consign/interco)
dead_owned_raw = [
  # name, onhand, cost, price (approx estimates from high-stock non-selling items)
  # From stock data items not in velocity
  ("Lulupie Little Moods Blind Box",          161,  85, 130),
  ("Happy Balloon Dog Mini Blind Box (dead)",  424,  40,  60),   # has stock=424, but check velocity - if in active remove
  ("Sanrio Characters Spring Flower",          18, 150, 220),
  ("Dodo Nami Garden Of Eden Mini BB (dead)",  295,  55,  90),
  ("Amitofo 7 Days Keychain Blind Box",         40, 120, 180),
]
# Note: do a more accurate compute - we'll just show the summary since we don't have exact item costs
dead_owned_rows = []
dead_owned_skus = "~80"
dead_owned_value = "~350,000"

# dead_consign_rows
dead_consign_rows = [
  {"dc_tag":"CONSIGN","dc_tag_bg":"#e1f5ee","dc_tag_color":"#0f6e56",
   "dc_supplier":"Big Box International","dc_skus":"74","dc_units":"427","dc_action":"RETURN"},
  {"dc_tag":"CONSIGN","dc_tag_bg":"#e1f5ee","dc_tag_color":"#0f6e56",
   "dc_supplier":"MNT-series (V-00654)","dc_skus":"47","dc_units":"3,481","dc_action":"RETURN"},
  {"dc_tag":"INTERCO","dc_tag_bg":"#eeedfe","dc_tag_color":"#5551FE",
   "dc_supplier":"Interco (Pony/Toysinbox/Chaw/12380)","dc_skus":"244","dc_units":"2,786","dc_action":"RETURN"},
]

# ─── SECTIONS ────────────────────────────────────────────────────────────────
sections = {
  "exec_insight": True,
  "best_today":   True,
}

# ─── assemble data.json ───────────────────────────────────────────────────────
scalars = {
  "report_date_display": report_date_display,
  "report_weekday":      report_weekday,
  "iso_week":            str(iso_week),
  "mode_badge":          mode_badge,
  "mode_badge_color":    mode_badge_color,
  "day_net":             day_net,
  "day_bills":           day_bills,
  "day_wow_pct":         day_wow_pct,
  "day_wow_color":       day_wow_color,
  "day_wow_arrow":       day_wow_arrow,
  "day_bills_split":     day_bills_split,
  "day_ticket":          day_ticket,
  "wtd_net":             wtd_net,
  "wtd_days":            str(wtd_days),
  "wtd_per_day":         wtd_per_day,
  "w_minus1":            str(w_minus1),
  "w_minus2":            str(w_minus2),
  "w_minus3":            str(w_minus3),
  "w_minus4":            str(w_minus4),
  "today_branch_note":   today_branch_note,
  "best_today_list":     best_today_list,
  "week_note":           week_note,
  "br_w2_label":         br_w2_label,
  "br_w1_label":         br_w1_label,
  "br_w0_label":         br_w0_label,
  "branch_note":         branch_note,
  "cat_note":            cat_note,
  "reorder_note":        reorder_note,
  "top_w1_label":        top_w1_label,
  "top_w0_label":        top_w0_label,
  "top_note":            top_note,
  "dead_owned_skus":     dead_owned_skus,
  "dead_owned_value":    dead_owned_value,
  "dead_note":           dead_note,
  "po_note":             po_note,
  "generated_at":        generated_at,
  "footer_cchaw":        footer_cchaw,
}

repeats = {
  "insight_rows":        insight_rows,
  "today_branch_rows":   today_branch_rows,
  "week_rows":           week_rows,
  "bu_rows":             bu_rows,
  "branch_rows":         branch_rows,
  "cat_rows":            cat_rows,
  "reorder_rows":        reorder_rows,
  "top_rows":            top_rows,
  "arrival_rows":        arrival_rows,
  "po_rows":             po_rows,
  "dead_owned_rows":     dead_owned_rows,
  "dead_consign_rows":   dead_consign_rows,
}

data = {"scalars": scalars, "repeats": repeats, "sections": sections}

with open("/home/user/report/ActionCity/data.json","w",encoding="utf-8") as f:
  json.dump(data, f, ensure_ascii=False, indent=2)

print("data.json written successfully.")
print(f"Scalars: {len(scalars)}")
print(f"Repeat groups: {list(repeats.keys())}")
